repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    - id: flake8
      name: flake8
      entry: poetry run ruff check
      language: system
      types: [ python ]
    - id: typecheck
      name: typecheck
      entry: poetry run ty check src/
      language: system
      types: [ python ]
