repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    - id: flake8
      name: flake8
      entry: poetry run ruff check
      language: system
      types: [ python ]
    - id: typecheck
      name: typecheck
      entry: poetry run ty check src/
      language: system
      types: [ python ]
